# Keras Basics

In [1]:
import numpy as np

In [2]:
import keras
from tensorflow.keras import Model

In [3]:
from numpy import genfromtxt
data = genfromtxt('bank_note_data.txt', delimiter=',')

In [5]:
data #0 and 1 shows authentic and false notes

array([[  3.6216 ,   8.6661 ,  -2.8073 ,  -0.44699,   0.     ],
       [  4.5459 ,   8.1674 ,  -2.4586 ,  -1.4621 ,   0.     ],
       [  3.866  ,  -2.6383 ,   1.9242 ,   0.10645,   0.     ],
       ...,
       [ -3.7503 , -13.4586 ,  17.5932 ,  -2.7771 ,   1.     ],
       [ -3.5637 ,  -8.3827 ,  12.393  ,  -1.2823 ,   1.     ],
       [ -2.5419 ,  -0.65804,   2.6842 ,   1.1952 ,   1.     ]])

In [6]:
labels = data[:,4]
labels

array([0., 0., 0., ..., 1., 1., 1.])

In [7]:
features=data[:,0:4]
features

array([[  3.6216 ,   8.6661 ,  -2.8073 ,  -0.44699],
       [  4.5459 ,   8.1674 ,  -2.4586 ,  -1.4621 ],
       [  3.866  ,  -2.6383 ,   1.9242 ,   0.10645],
       ...,
       [ -3.7503 , -13.4586 ,  17.5932 ,  -2.7771 ],
       [ -3.5637 ,  -8.3827 ,  12.393  ,  -1.2823 ],
       [ -2.5419 ,  -0.65804,   2.6842 ,   1.1952 ]])

In [8]:
X=features
y=labels

#### Splitting the Data into Training and Test
Splitting data into a train/test set. 

In [9]:
from sklearn.model_selection import train_test_split

In [10]:
X_train, X_test, y_train, y_test=train_test_split(X,y,test_size=0.33, random_state=42)

In [11]:
X_train

array([[-0.8734  , -0.033118, -0.20165 ,  0.55774 ],
       [ 2.0177  ,  1.7982  , -2.9581  ,  0.2099  ],
       [-0.36038 ,  4.1158  ,  3.1143  , -0.37199 ],
       ...,
       [-7.0364  ,  9.2931  ,  0.16594 , -4.5396  ],
       [-3.4605  ,  2.6901  ,  0.16165 , -1.0224  ],
       [-3.3582  , -7.2404  , 11.4419  , -0.57113 ]])

In [12]:
data.shape

(1372, 5)

In [13]:
X_test

array([[ 1.5691  ,  6.3465  , -0.1828  , -2.4099  ],
       [-0.27802 ,  8.1881  , -3.1338  , -2.5276  ],
       [ 0.051979,  7.0521  , -2.0541  , -3.1508  ],
       ...,
       [ 3.5127  ,  2.9073  ,  1.0579  ,  0.40774 ],
       [ 5.504   , 10.3671  , -4.413   , -4.0211  ],
       [-0.2062  ,  9.2207  , -3.7044  , -6.8103  ]])

In [14]:
y_train

array([1., 1., 0., 1., 0., 0., 1., 0., 0., 1., 0., 0., 0., 1., 1., 1., 0.,
       1., 1., 1., 0., 1., 1., 1., 0., 1., 0., 0., 1., 0., 0., 0., 1., 0.,
       1., 0., 0., 0., 0., 1., 1., 0., 0., 1., 0., 0., 1., 1., 1., 0., 0.,
       0., 1., 1., 1., 1., 1., 1., 1., 0., 0., 0., 0., 0., 0., 1., 0., 1.,
       0., 0., 0., 0., 1., 1., 0., 1., 1., 0., 1., 0., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 0., 1., 0., 0., 0., 0., 1., 1., 1., 0., 0.,
       0., 1., 0., 1., 1., 1., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 1., 1., 0., 1., 0., 1., 0., 0., 0., 0., 0., 1., 1., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 1., 0., 1., 0., 0., 1.,
       1., 0., 1., 0., 0., 1., 0., 1., 1., 0., 0., 0., 0., 0., 0., 1., 0.,
       0., 0., 1., 1., 0., 1., 1., 1., 1., 1., 0., 1., 1., 0., 0., 1., 1.,
       0., 1., 1., 0., 1., 1., 0., 0., 0., 0., 1., 0., 0., 1., 0., 1., 0.,
       0., 1., 0., 0., 1., 1., 0., 0., 1., 1., 0., 1., 1., 1., 0., 0., 0.,
       1., 0., 0., 1., 0.

In [14]:
y_test

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 1., 0., 1., 0., 1., 1.,
       1., 1., 1., 0., 0., 1., 0., 1., 0., 0., 1., 0., 0., 1., 0., 0., 1.,
       1., 0., 1., 1., 1., 0., 0., 1., 1., 0., 1., 1., 1., 0., 0., 1., 0.,
       0., 0., 0., 0., 1., 0., 0., 0., 0., 1., 0., 1., 0., 0., 0., 0., 0.,
       0., 1., 1., 0., 1., 0., 1., 0., 0., 1., 1., 1., 1., 0., 1., 0., 0.,
       0., 0., 1., 1., 0., 0., 0., 1., 1., 0., 1., 1., 0., 0., 0., 1., 0.,
       0., 0., 1., 0., 0., 1., 1., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.,
       0., 1., 0., 1., 0., 1., 0., 1., 1., 0., 1., 1., 0., 0., 0., 0., 0.,
       1., 0., 0., 0., 0., 0., 1., 0., 1., 1., 1., 1., 1., 0., 1., 1., 1.,
       0., 1., 0., 1., 0., 0., 0., 1., 1., 1., 1., 1., 0., 1., 0., 0., 0.,
       0., 0., 0., 1., 0., 0., 1., 1., 0., 0., 0., 0., 1., 0., 1., 0., 1.,
       1., 0., 0., 1., 0., 0., 1., 1., 1., 1., 0., 0., 1., 1., 1., 0., 0.,
       1., 1., 1., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 1., 1.,
       1., 1., 0., 1., 0.

### Standardizing the data
Usually when using Neural Networks, you will get better performance when you standardize the data.

In [15]:
from sklearn.preprocessing import MinMaxScaler

In [16]:
scaler_object=MinMaxScaler()

In [18]:
scaler_object.fit(X_train)

MinMaxScaler()

In [19]:
scaled_X_train=scaler_object.transform(X_train) #this operation gives us scaler transformed data

In [22]:
scaled_X_test=scaler_object.transform(X_test)

In [23]:
scaled_X_train #as we can see we have scaled the data

array([[4.44850688e-01, 5.14130449e-01, 2.18194638e-01, 8.50172258e-01],
       [6.53339968e-01, 5.82655745e-01, 9.93242398e-02, 8.17696322e-01],
       [4.81846700e-01, 6.69377018e-01, 3.61193167e-01, 7.63368407e-01],
       ...,
       [4.11050776e-04, 8.63104170e-01, 2.34046756e-01, 3.74261253e-01],
       [2.58284115e-01, 6.16029366e-01, 2.33861752e-01, 7.02643151e-01],
       [2.65661395e-01, 2.44444278e-01, 7.20316361e-01, 7.44775785e-01]])

In [24]:
X_train.max()

17.9274

In [25]:
scaled_X_train.max()

1.0000000000000002

In [26]:
X_train

array([[-0.8734  , -0.033118, -0.20165 ,  0.55774 ],
       [ 2.0177  ,  1.7982  , -2.9581  ,  0.2099  ],
       [-0.36038 ,  4.1158  ,  3.1143  , -0.37199 ],
       ...,
       [-7.0364  ,  9.2931  ,  0.16594 , -4.5396  ],
       [-3.4605  ,  2.6901  ,  0.16165 , -1.0224  ],
       [-3.3582  , -7.2404  , 11.4419  , -0.57113 ]])

In [27]:
scaled_X_train

array([[4.44850688e-01, 5.14130449e-01, 2.18194638e-01, 8.50172258e-01],
       [6.53339968e-01, 5.82655745e-01, 9.93242398e-02, 8.17696322e-01],
       [4.81846700e-01, 6.69377018e-01, 3.61193167e-01, 7.63368407e-01],
       ...,
       [4.11050776e-04, 8.63104170e-01, 2.34046756e-01, 3.74261253e-01],
       [2.58284115e-01, 6.16029366e-01, 2.33861752e-01, 7.02643151e-01],
       [2.65661395e-01, 2.44444278e-01, 7.20316361e-01, 7.44775785e-01]])

# Building the Network with Keras

Build a simple neural network

In [28]:
 from tensorflow import keras

In [29]:
from keras.models import Sequential
from keras.layers import Dense

In [34]:
#initiating model
model=Sequential()

model.add(Dense(4, input_dim=4, activation='relu'))

model.add(Dense(8, activation='relu'))

model.add(Dense(1, activation='sigmoid'))


relu is for non-linearity and since the other output is binary so we use sigmoid for binary output

Compile Model

In [35]:
model.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])

Fit (train) the model

In [36]:
model.fit(scaled_X_train, y_train, epochs=30, verbose=2)

Epoch 1/30
29/29 - 1s - loss: 0.7286 - accuracy: 0.4505 - 659ms/epoch - 23ms/step
Epoch 2/30
29/29 - 0s - loss: 0.7083 - accuracy: 0.3569 - 57ms/epoch - 2ms/step
Epoch 3/30
29/29 - 0s - loss: 0.6973 - accuracy: 0.4984 - 58ms/epoch - 2ms/step
Epoch 4/30
29/29 - 0s - loss: 0.6914 - accuracy: 0.5571 - 50ms/epoch - 2ms/step
Epoch 5/30
29/29 - 0s - loss: 0.6873 - accuracy: 0.5593 - 58ms/epoch - 2ms/step
Epoch 6/30
29/29 - 0s - loss: 0.6836 - accuracy: 0.5593 - 59ms/epoch - 2ms/step
Epoch 7/30
29/29 - 0s - loss: 0.6804 - accuracy: 0.5593 - 57ms/epoch - 2ms/step
Epoch 8/30
29/29 - 0s - loss: 0.6771 - accuracy: 0.5604 - 50ms/epoch - 2ms/step
Epoch 9/30
29/29 - 0s - loss: 0.6734 - accuracy: 0.5604 - 59ms/epoch - 2ms/step
Epoch 10/30
29/29 - 0s - loss: 0.6682 - accuracy: 0.5647 - 50ms/epoch - 2ms/step
Epoch 11/30
29/29 - 0s - loss: 0.6618 - accuracy: 0.5691 - 50ms/epoch - 2ms/step
Epoch 12/30
29/29 - 0s - loss: 0.6519 - accuracy: 0.5680 - 50ms/epoch - 2ms/step
Epoch 13/30
29/29 - 0s - loss: 0.63

In [37]:
model.predict(scaled_X_test)

15/15 [==============================] - 0s 2ms/step


array([[0.12666579],
       [0.35306057],
       [0.27202857],
       [0.3797243 ],
       [0.08605243],
       [0.05747477],
       [0.34746528],
       [0.03275454],
       [0.08344293],
       [0.29939547],
       [0.27620667],
       [0.59194976],
       [0.45704237],
       [0.7595009 ],
       [0.8141717 ],
       [0.13930833],
       [0.8085336 ],
       [0.81518793],
       [0.9102114 ],
       [0.7913198 ],
       [0.06838974],
       [0.22612546],
       [0.77508587],
       [0.04986104],
       [0.94668466],
       [0.05390362],
       [0.05712657],
       [0.79122543],
       [0.01150832],
       [0.0214042 ],
       [0.42653537],
       [0.24650271],
       [0.3093826 ],
       [0.9556651 ],
       [0.9073179 ],
       [0.03970997],
       [0.26188704],
       [0.518251  ],
       [0.63152415],
       [0.22764288],
       [0.24252768],
       [0.4466217 ],
       [0.52765495],
       [0.07638767],
       [0.9074684 ],
       [0.86359847],
       [0.8238181 ],
       [0.085

Predicting the unseen data

In [38]:
(model.predict(scaled_X_test) > 0.5).astype("int32")

15/15 [==============================] - 0s 3ms/step


array([[0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0],
       [1],
       [1],
       [0],
       [1],
       [1],
       [1],
       [1],
       [0],
       [0],
       [1],
       [0],
       [1],
       [0],
       [0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [1],
       [0],
       [0],
       [1],
       [1],
       [0],
       [0],
       [0],
       [1],
       [0],
       [1],
       [1],
       [1],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0],
       [1],
       [0],
       [1],
       [0],
       [1],
       [0],
       [0],
       [1],
       [1],
       [0],
       [0],
       [0],
       [0],
    

Evaluating model

In [39]:
model.metrics_names

['loss', 'accuracy']

In [40]:
model.evaluate(x=scaled_X_test, y=y_test)

15/15 [==============================] - 0s 2ms/step - loss: 0.3086 - accuracy: 0.8918


[0.3085672855377197, 0.8918322324752808]

In [45]:
from sklearn.metrics import confusion_matrix, classification_report

15/15 [==============================] - 0s 2ms/step


# Saving and Loading Model

In [47]:
model.save('deeplearningmodel1')

INFO:tensorflow:Assets written to: deeplearningmodel1\assets


INFO:tensorflow:Assets written to: deeplearningmodel1\assets


In [48]:
from keras.models import load_model

In [49]:
newmodel=load_model('deeplearningmodel1')

In [50]:
model.predict(X_test)

15/15 [==============================] - 0s 3ms/step


array([[1.96146566e-09],
       [6.07437047e-04],
       [3.67256653e-05],
       [8.72400560e-05],
       [1.08857914e-11],
       [2.38085722e-05],
       [2.23180905e-05],
       [2.35143827e-13],
       [1.70721322e-08],
       [1.37147504e-06],
       [2.12886580e-03],
       [8.31933022e-01],
       [4.54567857e-02],
       [8.94348979e-01],
       [9.99999225e-01],
       [5.30756597e-06],
       [9.81868029e-01],
       [9.90799308e-01],
       [9.38524544e-01],
       [9.89077628e-01],
       [1.07221697e-12],
       [1.33963184e-07],
       [8.79037738e-01],
       [1.54114274e-14],
       [9.99999940e-01],
       [2.43818393e-13],
       [1.16208313e-13],
       [8.66845727e-01],
       [5.24218595e-22],
       [2.64579426e-18],
       [6.65431619e-02],
       [5.89459660e-07],
       [2.49916247e-05],
       [1.00000000e+00],
       [9.99999702e-01],
       [2.29064750e-15],
       [6.91050373e-04],
       [8.00398648e-01],
       [9.70095694e-01],
       [1.46090372e-07],


Great job! You now know how to preprocess data, train a neural network, and evaluate its classification performance!